ignore: [ '**/lib/generated/', 'lib/generated/', 'lib/l10n/app_localizations*.dart', '**/*.g.dart', '**/*.gen.dart', '**/lib/di/', '**/lib/constants/', 'lib/constants/*.dart', 'lib/routers/router.dart' ]
coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%
